### ISSUE TITLE
what's the username, password of demo3.genieacs.com

### ISSUE THREAD

**Issue by sinkcup** [zaidka/genieacs-gui#14]
Hello, I see there is a demo (demo3.genieacs.com), but I can't find the username and password.

and what's the port, path of genieacs, this config for freecwmp openwrt is right?

    config acs
        option scheme 'http'
        option username 'freecwmp'
        option password 'freecwmp'
        option hostname 'demo3.genieacs.com'
        option port '37547'
        option path '/openacs/acs'

**Comment by akcoder** [comment]
Try admin/admin

The port is 7547. Not sure if http or https. Point your browser at it. When you have the right scheme you will get a "method not allowed" (because it wants post, not get)

-dan

**Comment by zaidka** [comment]
That's a demo used for commercial purposes. I wonder how you found it though :)

**Comment by sinkcup** [comment]
^_^ I like google
