### ISSUE TITLE
Getting started with the GeneiACS. Do i need to configure any files before i getting the GUI ?

### ISSUE THREAD

**Issue by Siddeshi** [zaidka/genieacs-gui#16]
Hello there,

Actually I'm trying to use genieacs on docker container. It seems genieacs is working fine in my system. But in the URL when I type this( http://172.17.0.4:7547/ ), it gives me 405 Method Not Allowed.

When check that error on this site ( http://100pulse.com/http-statuscode/405.jsp ), they are saying that you may be attempting to run a script that is not supported.

Help me what script should I change to make this works.

Thank you.

**Comment by akcoder** [comment]
This is by design. The CPE POST's data to that endpoint.

If you are wanting to see what CPE's have registered with the ACS, you need
to install and configure GenieACS-GUI. The gui listens on port 3000 by
default.

-dan

**Comment by Siddeshi** [comment]
@akcoder 
Yes, I have installed GinieACS-GUI. The problem is that, can I access the gui to the outside world from the docker container?
For that, what I need to do ?
I have tried with 
1. PORT exposing technique.
2. I have installed a brower inside the container and tried to access it. But browser itself doesn't open for the command firefox. Throws an error like display=10 (also 11, 99 etc..) not found.
3. I have tried to change the IP address of the container to static IP, then also throws an exception like operation not permitted.
4. For port 3000, it is saying that can't establish the conecton, (all the required servers are runing in the container).
Tell me, what might be the solution or suggestion.

Thank you.

**Comment by Siddeshi** [comment]
How to access this port 3000 ?

**Comment by akcoder** [comment]
Lets take this over to the mailing list.

I'm not familiar with Docker.

But what I can tell you is that you need the following ports exposed
externally for the CPE: 7547, and 7567.  Port 7557 should *not* be exposed
to the public internet.

Port 3000 is where the GUI runs, provided you have GenieACS-GUI installed
(and haven't changed the port).

-dan

**Comment by zaidka** [comment]
Port 3000 is not GenieACS specific. It's just the port that the development server that ships with Rails uses (i.e. WEBick). You can get it to listen to port 80, but WEBrick is not recommended for production use anyway. Use something like Apache or Nginx instead.
