### ISSUE TITLE
Problems when running with apache + https + proxy 

### ISSUE THREAD

**Issue by jpereira** [zaidka/genieacs-gui#17]
Hi,

I have installed in my server an instance of GenieACS and GenieACS-GUI running in localhost interface. And i have an apache runs in proxy mode providing access in my external interface.

1) Port 80 listening to 7547 (cwmp server)
![screenshot from 2015-03-03 14 00 09](https://cloud.githubusercontent.com/assets/254448/6467535/a736ba12-c1ad-11e4-9bba-4e9a0c97cc5b.png)

2) Port 443 listening to 3000 (cwmp gui)
![screenshot from 2015-03-03 14 01 04](https://cloud.githubusercontent.com/assets/254448/6467547/bff3eee4-c1ad-11e4-8426-f9086afe5455.png)

The problem is because during use of GenieACS-GUI some links give me wrong redirects like when trying to apply a new tag.

![screenshot from 2015-03-03 13 16 19](https://cloud.githubusercontent.com/assets/254448/6467564/e9031684-c1ad-11e4-83cb-b36eae55ab2b.png)

It's possible to note that i'm on https then after click i got the redirect to http in "Location" section shown above.

p.s: I don't have any rewrite rules or something like that.

**Comment by akcoder** [comment]
I don't have anything to add to the main part of your issue, but don't
forget to reverse proxy, or allow directly access to port 7567 so file
downloads (firmware upgrades, etc) to the CPE work correctly.

-dan

**Comment by jpereira** [comment]
Dan,

 You can note that problem is in the GenieAcs-GUI. after i click in the
link "tag", the site makes a POST request and receive an 302 (Location) to
same host but changing from the https to http... check again the last image
that may you can note.

On Tuesday, March 3, 2015, Dan Morphis <notifications@github.com> wrote:

> I don't have anything to add to the main part of your issue, but don't
> forget to reverse proxy, or allow directly access to port 7567 so file
> downloads (firmware upgrades, etc) to the CPE work correctly.
>
> -dan
>
> On Tue, Mar 3, 2015 at 8:04 AM, Jorge Pereira <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Hi,
> >
> > I have installed in my server an instance of GenieACS and GenieACS-GUI
> running in localhost interface. And i have an apache runs in proxy mode
> providing access in my external interface.
> >
> > 1) Port 80 listening to 7547 (cwmp server)
> > [image: screenshot from 2015-03-03 14 00 09]
> > <
> https://cloud.githubusercontent.com/assets/254448/6467535/a736ba12-c1ad-11e4-9bba-4e9a0c97cc5b.png
> >
> >
> > 2) Port 443 listening to 3000 (cwmp gui)
> > [image: screenshot from 2015-03-03 14 01 04]
> > <
> https://cloud.githubusercontent.com/assets/254448/6467547/bff3eee4-c1ad-11e4-8426-f9086afe5455.png
> >
> >
> > The problem is because during use of GenieACS-GUI some links give me
> wrong
> > redirects like when trying to apply a new tag.
> >
> > [image: screenshot from 2015-03-03 13 16 19]
> > <
> https://cloud.githubusercontent.com/assets/254448/6467564/e9031684-c1ad-11e4-83cb-b36eae55ab2b.png
> >
> >
> > It's possible to note that i'm on https then after click i got the
> > redirect to http in "Location" section shown above.
> >
> > p.s: I don't have any rewrite rules or something like that.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/zaidka/genieacs-gui/issues/17>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zaidka/genieacs-gui/issues/17#issuecomment-76993056>.
>


-- 
Sent from my iPowerBall®

**Comment by zaidka** [comment]
IIRC, there's a configuration that you can set to let Rails generate URI using HTTPS. However, the Rails/Rack server you're using (WEBRick) is not meant for production use anyway.

**Comment by jpereira** [comment]
I fixed it using the option:

RequestHeader set X_FORWARDED_PROTO 'https'

in my apache-ssl-proxy-settings, thanks!
