### ISSUE TITLE
Run by 'rails server -d' can't show the normal web page

### ISSUE THREAD

**Issue by garyyu** [zaidka/genieacs-gui#28]
If I run 'rails server' on the shell, I can open the web page successfully, everything seems good.
But when I want to run it in background by 'rails server -d', the web page always tell an error "No such file or directory @ rb_sysopen - config/graphs.json.erb". Please see the enclosed screenshot.

My environment: Ubuntu 14.04  x64.
# uname -a
Linux ubuntu 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

# rails -v
Rails 4.1.4

![screen shot 2015-08-30 at 10 12 43 pm](https://cloud.githubusercontent.com/assets/1852227/9567618/45321f00-4f65-11e5-9949-f1971143434c.png)

**Comment by garyyu** [comment]
Great speed!  Thanks Zaidka!
And I verified the fix works.

**Comment by zaidka** [comment]
You're welcome. Keep in mind that that's a development server and is not best suited for production. Better to use something like Puma or Passenger.
