### ISSUE TITLE
How to print debug message on genieacs-gui?

### ISSUE THREAD

**Issue by MikeAtQuanta** [zaidka/genieacs-gui#29]
Dear sir,

  I am a new beginner for genieacs.
Would you kindly advise me the steps to enable debug log on genieacs-gui, how to add a log on genieacs-gui and how to find its output log? Many thanks.

Mike

**Comment by zaidka** [comment]
I believe if you run it in development mode (i.e. rails s) you'll get debug messages enabled by default. Check the config parameters under "config/environments" directory.
