### ISSUE TITLE
Software Update Preset

### ISSUE THREAD

**Issue by lfroehlich** [zaidka/genieacs-gui#3]
Hi,

i add a new Firmware Upgrade Image on the Files tab.
Type: 1 Firmware Upgrade Image
Manufacturer: AVM
Product class: FRITZ!Box
Version: 84.06.03

I could update a single Device per push file button on the device page.
But the Preset don't match.

The Preset looks:

Name: Update_Test
Weight: 1

Precondition
MAC: MAC of the FRITZ!Box i want update

Configurations
Software version: 84.06.03

How can i configure Updates for all Devices don't match latest Firmware?

kind regards,
Lars

**Comment by ika777** [comment]
Hello, we need to make a task for ACS server to  push FW updates on some ampunt of cpes, i woder if it is possible to push this files without running this task per CPE, and can you please advice the best way to push FW update for matched CPEs
