### ISSUE TITLE
new db filed 

### ISSUE THREAD

**Issue by metalsoft10** [zaidka/genieacs-gui#30]
how i can add new filed to device db 
for ex there are _tag
i want add a new db filed on device  >> router owner 
that i can filter devices with it

**Comment by zaidka** [comment]
This isn't related to genieacs-gui. Please use the mailing list.

**Comment by metalsoft10** [comment]
ok how to filter with multi serial No

**Comment by zaidka** [comment]
Please don't spam the issue tracker. This place is for bug reports only.
