### ISSUE TITLE
Full SSL Support for GenieACS Webui

### ISSUE THREAD

**Issue by fhocorp** [zaidka/genieacs-gui#34]
Hello

I am looking to enable SSL encryption on the GenieACS Webui.

I have tried this https://github.com/zaidka/genieacs/wiki/GenieACS-Auth-Config  but some of the links in the Webui (like the refresh and the reboot buttons redirect to clear HTTP. The redirection by nginx is made but i am afraid that the redirection is in clear ( i can see it on wireshark for example)

How to enable natively SSL in the webui without using nginx ?

Best Regards

**Comment by zaidka** [comment]
There are many ways to deploy a Rails app so I can't answer that without knowing how you have deployed it. But in the end you have to use a web server like nginx or Apache. The development web server that you start with "rails s" doesn't support SSL.

Please post to the mailing list for support questions like this. The issue tracker is for bugs and feature requests.
