### ISSUE TITLE
Creating groups for CPE

### ISSUE THREAD

**Issue by fhocorp** [zaidka/genieacs-gui#35]
Hello

I am searching for the option for creating groups for the graphs display in the home page of GenieACS

![image](https://cloud.githubusercontent.com/assets/6709117/13282263/5db0264e-dae8-11e5-99f7-7f1c2bba1c66.png)

Also In the snapshot of the homepage of the genieACS website there is a "log" menu and "Base Stations" menu that i can't find in my configuration.

**Comment by zaidka** [comment]
Please use the mailing list. The mailing list is where you can get help. This issue tracker is where you *give* help by pointing out bugs or contribute PR.
