### ISSUE TITLE
Setting up the genieacs 

### ISSUE THREAD

**Issue by umbur** [zaidka/genieacs-gui#41]
Hello,
First of all I apologize for opening an issue, because I am pretty sure that this is not actually an issue of the program, but rather the issue is a local one -- of installing or setting up it(genieacs) in "our" environment.
The main purpose to use the program is that we have some CPE's(DSL modems) which have the manually configs(with the NAT and the http access enabled) so that we could manage them remotely(mainly through the web interface), the issue, however occurs when those CPE's are reset(which occurs quite soon); in that state(reset, with bridge interface) we no longer can access them(so that to reconfigure them), however we are able to gain some details: such as -- the mac address of the reset device(DSL modem).
Recently we were thinking about the TR069 protocol; and after searching the Internet I come across to your program; so I was browsing the installation guides hoping to install and test it..
The last, so far looking relatively good instruction which I was/am using is this one: https://github.com/zaidka/genieacs/wiki/Installation-in-Ubuntu-14.04-&-15.10
Here is the things which I've done:
I've installed the Ubuntu 14.04 LTS;
Using the OS's built-in terminal, have installed the Node.js, Redis, MongoDB;
Then I've installed the GenieACS, and the GenieACS GUI.
Then I've again, was following the instructions for my next steps..  
I was able to run the gui(the web), but then have encountered an error message(I've also tried to edit "development.rb" file, in particular: the host and the port fields, but it was not helping.. ), similar to this one:https://github.com/zaidka/genieacs-gui/issues/1       
here is the screen shot of mine:
![screenshot from 2016-04-27 10 33 00](https://cloud.githubusercontent.com/assets/18226344/14843921/dd872a54-0c64-11e6-9fb3-5e05482f8819.png)
Would really appreciate the response; thanks in advance!

One important update: I was able to run the program using this guide: https://github.com/zaidka/genieacs/wiki/Script-Installation---Ubuntu
here is the screen shot now: 
![screenshot from 2016-04-27 12 10 28](https://cloud.githubusercontent.com/assets/18226344/14845818/c816877a-0c71-11e6-8156-366f63668deb.png)
 

Now I am looking forward to actually configure it...

**Comment by okraits** [comment]
For topics more about configuration/usage rather than software issues please use the mailing list.

**Comment by umbur** [comment]
Hello okraits, thanks for reply. I've posted a message at: http://permalink.gmane.org/gmane.network.genieacs.user/713
