### ISSUE TITLE
Devices not refresh or can't be controlled by Genieacs after upgrade

### ISSUE THREAD

**Issue by fhocorp** [zaidka/genieacs-gui#49]
Hello

Recently we have updated our GenieACS Server to the last version in the Github directory (GenieACS/1.1.0-alpha).

But after the upgrade, we are unable to connect our devices to the ACS Server. The GUI and the CWMP server seems working but the devices did not refresh in the Gui of GenieACS

Here is some logs we have found :

Started GET "/devices/7C4FB5-Yabox-J145002104" for 77.132.5.221 at 2016-09-01 20:46:43 +0200
Cannot render console from 77.132.5.221! Allowed networks: 0.0.0.0, 127.0.0.0/127.255.255.255, ::1
Processing by DevicesController#show as HTML
  Parameters: {"id"=>"7C4FB5-Yabox-J145002104"}
  Rendering devices/show.html.erb within layouts/application
  Rendered devices/_tags.html.erb (2.4ms)
  Rendered devices/_last_inform.html.erb (142.8ms)
  Rendered devices/_object_table.html.erb (12.9ms)
  Rendered devices/_summary_group.html.erb (32.7ms)
  Rendered devices/_tasks.html.erb (2.6ms)
  Rendered devices/_params.html.erb (1116.8ms)
  Rendered devices/_commands.html.erb (7.0ms)
  Rendered devices/show.html.erb within layouts/application (1359.7ms)
  Rendered layouts/_menu.html.erb (6.5ms)
Completed 200 OK in 2878ms (Views: 2706.1ms | ActiveRecord: 0.0ms)

Currently we have done a downgrade from a backup to the older version.

**Comment by DrumSergio** [comment]
Hi, @fhocorp !

It seems you have not installed GenieACS-GUI v1.1 . They both have to be deployed altogether.

Anyway, this GitHub issue tracker is not for getting help with installation/deployment. It is meant to talk about bugs. If you want more help, there in the mailing list you will find it: http://lists.genieacs.com/mailman/listinfo

**Comment by fhocorp** [comment]
@DrumSergio Thanks for your answer ;)
