### ISSUE TITLE
Errno::ECONNREFUSED in HomeController#index 

### ISSUE THREAD

**Issue by mushir3589** [zaidka/genieacs-gui#53]
Hello,
I'm new to GenieACS and Ruby. I followed the instructions to set it up on my own and it GUI. Thanks in advance
![errornew](https://cloud.githubusercontent.com/assets/23330990/20090420/0a49672c-a5b3-11e6-9a39-670a89445a8e.png)

**Comment by zaidka** [comment]
Looks like genieacs-nbi is not running.

Please use the community mailing list for help. This is strictly for bug reports.
