### ISSUE TITLE
Error sending file

### ISSUE THREAD

**Issue by djxoxe** [zaidka/genieacs-gui#57]
Hello

I am trying to send a configuration file to a CPE but I get this error they see in the screenshot capture.

How could I solve it?

Thank you very much.

![error mongodb](https://cloud.githubusercontent.com/assets/25243945/22144557/72548a5c-defe-11e6-9e8e-70bc9d6b017d.jpg)

**Comment by DrumSergio** [comment]
Hi, @djxoxe !

Better to talk about it in the mailing list: http://lists.genieacs.com/mailman/listinfo 

Thank you!

**Comment by djxoxe** [comment]
Thank you.
