### ISSUE TITLE
Incorrect Connection Request Credentials

### ISSUE THREAD

**Issue by djxoxe** [zaidka/genieacs-gui#61]
Hello friends,

Does anyone know why I get this error when I try to upload a file to a CPE?

In advance, thanks.
![sin titulo](https://cloud.githubusercontent.com/assets/25243945/22892600/77550180-f213-11e6-835f-8928a0ead3bc.jpg)

**Comment by akcoder** [comment]
Because your CPE is set to require credentials to connect and you have the
wrong ones set in the auth.js file

**Comment by djxoxe** [comment]
Thank you Akcoder.

How do I do so that the CPE does not require credentials or in what line of the auth.js I put the credentials that the CPE is asking for?

Greetings.

**Comment by djxoxe** [comment]
Thank you.

**Comment by akcoder** [comment]
If you do t have connection auth turned on in the CPE then it's time to break out wireshark or set the DEBUG flag to true in config.json (remember to restart the cwmp process). Then look in the debug folder for the ID of your CPE. That file will contain the raw HTTP conversion between the cwmp and CPE. 

-dan

**Comment by akcoder** [comment]
GitHub is for defect tracking, not support requests. Please take your support request to the mailing list. 

-dan
