### ISSUE TITLE
Events GenieACS

### ISSUE THREAD

**Issue by djxoxe** [zaidka/genieacs-gui#63]
Hello friends.

I would like to know how to correctly set the events. How do you write them to work?

1. 1 BOOT
2. 1_BOOT
3. "1 BOOT"
4. '1 BOOT'
5. "1_BOOT"

What is the correct nomenclature?

Thanks and regards.

**Comment by okraits** [comment]
For questions about how to use GenieACS please use the mailing list as github issues are meant for topics related to development.

**Comment by djxoxe** [comment]
Thank you okraits. I will do it
