### ISSUE TITLE
Getting error genieacs 

### ISSUE THREAD

**Issue by hkachhia** [zaidka/genieacs-gui#67]
Hello,
I have followed steps for configured genieacs from https://tr069.wordpress.com/2014/03/26/installing-genieacs-on-precise-pangolin/ website but I am getting below error 
![geniacs-error](https://cloud.githubusercontent.com/assets/12659639/23989676/65f4c6a6-0a59-11e7-8063-d887469e4a94.PNG)

Can you please help me for  this.

**Comment by zaidka** [comment]
Not sure why you're posting this in genieacs-gui issue tracker when it's related to genieacs core. Anyways, this isn't a bug so please use the mailing list.
