### ISSUE TITLE
How to enable HTTPs for Genieacs-gui 

### ISSUE THREAD

**Issue by pdthang59** [zaidka/genieacs-gui#87]
Dear community

Do you know any tutorial to enable HTTPs for Genieacs-gui ? 

Thank you so much

**Comment by DrumSergio** [comment]
Just as simple as googling 'https ruby on rails': https://www.pluralsight.com/guides/ruby-ruby-on-rails/using-https-with-ruby-on-rails

Anyway, this is an issue tracker, we usually don't provide help of this kind here. Better for these type of questions to be in the mailing list: http://lists.genieacs.com/mailman/listinfo

**Comment by akcoder** [comment]
Github is for defect tracking, not support requests. Please take this to
the mailing list.

**Comment by pdthang59** [comment]
Thank you. I will re-sent
